### PR TITLE
CSP_MAX_DELAY & Interrupts handling on POSIX Queues

### PR DESCRIPTION
**Pull request by pacheco017**
Changes:
- Retries on interrupts (`EINTR`) when waiting on queue operations.
- Special handling of `CSP_MAX_DELAY` as timeout of queue operations.

### CODE REVIEW

**Review by johandc — APPROVED** [review]
Looks good.

Seems simple enough to merge into mainline for stability testing before the next release.

**Comment by jledet** [comment]
Looks OK to me as well. I have one minor nitpick. I don't like these types of comparisons:

`if (PTHREAD_QUEUE_OK == ret)`

I know it's an attempt to avoid accidental assignments, but the style differs from the rest of the codebase. This type of error is also caught by gcc with -Wparentheses (included in -Wall).

But I like the fixes, so I agree with Johan that this should be merged. I can add a style cleanup patch later then.

**Comment by perwulff** [comment]
Ok by me. I would prefer to use CLOCK_MONOTONIC, instead of CLOCK_REALTIME, but that may a relic from before it was possible to set the clock on the pthread_condattr_t.

**Comment by pacheco017** [comment]
@perwulff: I also prefered `CLOCK_MONOTONIC` so I had the changes ready on another branch, now merged in this PR (I did a `--ff-only` merge, so github shows https://github.com/libcsp/libcsp/pull/77/commits/94140c30169b4f4e33ca333073326b63da497da0 before your feedback, sorry if that's confusing).

@jledet: I believe that style consistency is very important, so there is no need to postpone the changes. I think https://github.com/libcsp/libcsp/pull/77/commits/b6581d81071063f187fd58fdade72343795d5b9b addresses your comment.

Thanks for the review!

**Comment by johandc** [comment]
Perfect, looks ready for a merge.

**Pull request merged**
