### PR TITLE
Remove duplicate definition of csp_hex_dump()

### PR DESCRIPTION
**Pull request by dimitrovand**
csp_hex_dump() is already defined for all possible values of CSP_ENABLE_CSP_PRINT in csp_hex_dump.c

### CODE REVIEW

**Comment by yashi** [comment]
Hi @dimitrovand,

Thanks for the PR.  Please write your comment as a git commit log.  Not here in GitHub.  GitHub will take your git commit log and puts in the description area if your PR only has one commit.  Please fix your commit and push it again.  Thanks.

**Comment by yashi** [comment]
would you please fold the body so that length is less than 72 or so?

Please see the example at https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

**Comment by yashi** [comment]
Thanks for comment fixes.

Now onto the techinical part.  I'd say that `csp_hex_dump.c` should not be compiled when `CSP_ENABLE_CSP_PRINT == 0`.  However, we want to keep inline version of both funcitons just to keep the symbols for applications.

WDYT?

**Comment by dimitrovand** [comment]
No worries.

On first glance, I can't see any major/critical drawbacks in using any of these two solutions. One is adding to the build process, while the other - source code itself. I did the change led by the fact `csp_hex_dump.c` was already compiled unconditionally by all supported build systems, as it is done for other options (such as `RDP` and `PROMISC`). 
On a second pass over the source code, there seems to be no unified way of handling such scenarios. I guess this is purely a design decision, but as a library user - one would rather not like to deal with a complex build process (especially when having to recreate the existing one for a different build system), in my opinion.

**Comment by yashi** [comment]
@dimitrovand In your comment, you mentioned that 'one would rather not like to deal with a complex build process.' Could you please provide more details or examples of what you consider a complex build process in this context?

Just to clarify, the conditional compilation we're discussing involves adding or removing the file.  And we already do that for other files.

Thanks.

**Comment by dimitrovand** [comment]
Hello @yashi ,
By complex build process, I mean complex CMakeLists. You're right that the current implementation of it is not complex, and it's not the 1st time. I can easily redo it as suggested, but would you like this done also in all places where another approach has been used?

**Comment by yashi** [comment]
> I can easily redo it as suggested, but would you like this done also in all places where another approach has been used?

Would you please share which are in your mind?  If they are the same type of problem, I'd love them to be fixed.  But want to make sure we are on the same page.  I don't want to waste you precious time otherwise.

**Comment by dimitrovand** [comment]
They are not the exact same problem, but `csp_promisc.c` `csp_rdp.c` `csp_rdp_queue.c` are also being compiled even when their corresponding enable/disable option is set to 0 (same as `csp_hex_dump.c`).

**Comment by yashi** [comment]
@dimitrovand Thanks. They can also be compiled conditionally.

**Comment by yashi** [comment]
@dimitrovand Please fill in commit message.  Please see #516 for more info.

**Review by yashi — CHANGES_REQUESTED** [review]
Thanks!

It's a nitpick but please do spell check on commit message.  Something like this should do:

  > When CSP_ENABLE_CSP_PRINT == 0, we can skip the compilation of csp_hex_dump.c due to the fact that there is already an inline implementation of csp_hex_dump() in csp.h. Due to the same reason, we can also remove the empty version of csp_hex_dump() implementation from csp_hex_dump.c.

I'm doing build test now but everything else LGTM.

**Review by yashi — APPROVED** [review]
LGTM.  Thanks!

**Pull request merged**
