### PR TITLE
Add option to build with FreeRTOS on embedded platforms

### PR DESCRIPTION
**Pull request by gp-9**
- Add CMakeLists.txt file for FreeRTOS arch/freertos directory
- Add cmake logic to specify "FreeRTOS" as a target option in order to find `FreeRTOS.h` and `FreeRTOSConfig.h` files
- Add cmake option and c preprocessor directives to check and include the correct `endian.h` path. Right now the only custom `endian.h` paths are `sys/endian.h` and `machine/endian.h`, specified through a compile-time define option; if no custom path is provided and the option is not set, this check falls back to the original `endian.h`.

### CODE REVIEW

**Comment by yashi** [comment]
Wow, and hi @gp-9!

I'm super happy to see FreeRTOS support in CMake.

Regarding `endian.h`, we have removed `csp_endian.h` in favor of picolibc a while ago. You seem to be using newlib, which has two `endian.h`.  My understanding of two `endian.h` in newlib is that `sys/endian.h` provides user facing one and `machine/endian.h` is low level one.  That's why `sys/endian.h` includes `machine/endian.h`.  Please enlighten me why you need both.  You can find some details about removal of `csp_endian.h` [here](https://github.com/libcsp/libcsp/issues?q=is%3Aissue+endian.h+is%3Aclosed).

Last but not least, would you mind helping me test the PR by providing step-by-step commands for building a "hello world" program against FreeRTOS using libcsp? It'd be great if you could add a GitHub Action to build the test. Running the built binary and tests on QEMU would be really nice. :smiley:

**Comment by gp-9** [comment]
Hi,

I'm sorry I didn't respond earlier. Regarding newlib, I've checked and, in fact, just `sys/endian.h` is necessary so I've changed the config option in cmake to CSP_USE_NEWLIB. 

Concerning the "hello world" program, I'm currently working on a simple project using libcsp similar to `csp_server_client.c`. Where should I put this project?

**Comment by yashi** [comment]
> Concerning the "hello world" program, I'm currently working on a simple project using libcsp similar to `csp_server_client.c`. Where should I put this proje

We have `contrib/zephyr/`.  So how about `contrib/freertos/`?

**Comment by yashi** [comment]
And we don't want any 'merge commits' or 'micro-commits'. All we need are commits that each represent logical changes. Review feedback and typo fixes can be squashed into the appropriate commit.  If you need help, please let me know.

**Comment by gp-9** [comment]
Ok, thank you for your help

**Comment by yashi** [comment]
It looks good to me except that

- still has a merge commit 0fa539657fd86d2aab34115aae37f361e7f5b6c9
- the first commit doesn't have a commit log

**Comment by yashi** [comment]
Thanks. The commits LGTM.

I'm waiting for step by step command instruction to test build against FreeRTOS.

**Comment by gp-9** [comment]
Hi,
I'm closing this pull request because I can't work on this project any longer.

**Pull request closed without merging**
