### PR TITLE
removing duplicate declaration of csp_buffer_init(), fix typos, run clang-format on whole file

### PR DESCRIPTION
**Pull request by dimitrovand**
Removing a duplicate declaration of csp_buffer_init().
Fix typos in some methods' docs.
Run clang-format on whole file to ensure code style consistency.

### CODE REVIEW

**Comment by yashi** [comment]
Hi,

Thanks for the PR.  But please do not squash logical changes in one commit.  
https://www.kernel.org/doc/html/latest/process/submitting-patches.html#separate-your-changes

Here is some guidelines:
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

gitlint might help
https://github.com/jorisroovers/gitlint

**Comment by yashi** [comment]
FYI: 
- #516

**Comment by dimitrovand** [comment]
Thanks @yashi , shall I open new PRs and close this one?

**Comment by yashi** [comment]
You don't need to close this PR.  What you have to do is to split the commit to three, and push it here.

**Comment by yashi** [comment]
Thanks!

**Pull request merged**
