### PR TITLE
Update Waf to 2.0.14

### PR DESCRIPTION
**Pull request by daniellandau**
Old Waf doesn't work with Python 3.7 because of PEP 479.

https://stackoverflow.com/a/51701040/1517818

### CODE REVIEW

**Comment by perwulff** [comment]
hi Daniel,
Thanks for the contribution.
Only the self-extracting Waf file should be added to GiT - not all the extracted files.

**Comment by daniellandau** [comment]
Found it, now fixed.

**Comment by johandc** [comment]
We should target this on the release branch instead.

**Comment by daniellandau** [comment]
@johandc I clicked the "Allow edits from maintainers" so feel free to change the base branch.

**Pull request merged**
