### PR TITLE
src/csp_rtable_stdio.c: replace strnlen, strtok_r by ISO_C versions

### PR DESCRIPTION
**Pull request by fjmolinas**
Alternative to https://github.com/libcsp/libcsp/pull/362, simply using non re-rentrant `strtok_r` and regular `strlen`

### CODE REVIEW

**Comment by johandc** [comment]
Using the non reentrant version of strtok pulls in a lot of unwanted thread synchronization and safety stuff from newlib such as the impure ptr.

See this topic
https://embdev.net/topic/129813

ISO C is not a target of CSP in itself. Where it makes sense, such as safer strnlen we should use that.

**Comment by fjmolinas** [comment]
Should I close both related PRs and patch locally then?

**Comment by johandc** [comment]
Why don't you build with C99? Or GNU99?

**Comment by fjmolinas** [comment]
> Why don't you build with C99? Or GNU99?

`strnlen` is not part of the c99 standard, there is `strlen_s` but only in c11, but building with `gnu99` should do. Thanks!

**Pull request closed without merging**
