### PR TITLE
Buildall.py: Add meson build system

### PR DESCRIPTION
**Pull request by yashi**
We use the meson build system to build the develop branch and we'd like to run our CI with it.  This PR is preparation of it.  All functionality should have been implemented except `.travis.yml`.

This is related to #214.

### CODE REVIEW

**Review by johandc — CHANGES_REQUESTED** [review]
These seemingly unused variables are exported and used from the master projects, whenever CSP is used as a subproject. (Which it always is)

Otherwise your changes look good.

**Comment by yashi** [comment]
@johandc, Thanks, I didn't notice that!

A bit of reading about `declare_dependency()` taught me that Meson version 0.56 added a new function, [as_link_whole](https://mesonbuild.com/Release-notes-for-0-56-0.html#depas_link_whole), to dependency object.

You can, in a parent project, now do
```meson
executable('asdf',
	   'main.c',
	   dependencies : csp_dep.as_link_whole())
```

And you don't need `csp_dep_whole`. Do you still want to keep the varible?

**Comment by yashi** [comment]
I've updated this PR without "meson.build: Remove unused variables".  It should be ready to merge.

I'll create another PR if you want to kill `csp_dep_whole`.

**Comment by johandc** [comment]
> @johandc, Thanks, I didn't notice that!
> 
> A bit of reading about `declare_dependency()` taught me that Meson version 0.56 added a new function, [as_link_whole](https://mesonbuild.com/Release-notes-for-0-56-0.html#depas_link_whole), to dependency object.
> 
> You can, in a parent project, now do
> 
> ```meson
> executable('asdf',
> 	   'main.c',
> 	   dependencies : csp_dep.as_link_whole())
> ```
> 
> And you don't need `csp_dep_whole`. Do you still want to keep the varible?

That's a good idea. Much cleaner like that. Yes let's get rid of link whole then.

**Pull request merged**
