### PR TITLE
Cast all `printf("%p")` values to void pointers

### PR DESCRIPTION
**Pull request by parker-research**
Reason: gcc gives the following build warning:

```
format '%p' expects argument of type 'void *', but argument 3 has type 'csp_socket_t *' {aka 'struct csp_conn_s *'} [-Wformat=]
```

### CODE REVIEW

**Comment by yashi** [comment]
Hi @parker-research,

Thank you for the PR. Please update the commit message according to [the guideline](https://libcsp.github.io/libcsp/git-commit.html#commit-message-guidelines).

Also, it might be a good idea to reference the C standard, or the draft thereof, N2310.

**7.21.6.1 The `fprintf` function**
> If any argument is not the correct type for the corresponding conversion specification, the behavior is undefined.

I have installed gitlint to `libcsp-1`. So please rebase on top of it.

Thanks,

**Comment by parker-research** [comment]
All three of my recent PRs (#645, #646, #647) had the purpose of working toward building without errors with `-Wpedantic`. 

Should I combine them  into a single PR/commit, @yashi? Any advice?

**Comment by yashi** [comment]
No need to combine them in one PR.  Separate PRs are fine. I need commit messsages in all though.

**Comment by parker-research** [comment]
Sorry, I don't understand what's wrong with the commit message. As far as I can tell, it conforms to your guideline, so the issue might be that the guideline is missing a detail.

For contributions from occassional contributors, have you considered doing a GitHub "Squash and Merge" instead? It lets you pick/rewrite the commit message at merge time.

**Comment by yashi** [comment]
If you go https://github.com/libcsp/libcsp/actions/runs/10434343582/job/28898021792 by clicking "Details", you see

> 8: B1 Line exceeds max length (116>80): "> If any argument is not the correct type for the corresponding conversion specification, the behavior is undefined."

So, your commit message has a long line, 116 chars, which should be less than 80.

**Comment by parker-research** [comment]
Thanks! Fixed!

**Comment by yashi** [comment]
@parker-research It seems we have a conflicts. Would you please fix it?

**Comment by parker-research** [comment]
Fixed! Thanks

**Pull request merged**
