### PR TITLE
Fix ci build

### PR DESCRIPTION
**Pull request by yashi**
Let's see how it goes.

### CODE REVIEW

**Review by johandc — APPROVED** [review]

**Comment by yashi** [comment]
Oops, thank you for merging it but the PR was still WIP and a draft. 😁

I couldn't finish it by the last train but t seems we still have a execution problem.

I'll finish up tomorrow.

**Comment by johandc** [comment]
I was hoping the build would work after the merge. Because you had added examples to the target names.
At least CSP now compiles it's just a matter of fixing the examples. I don't think you need the examples on the target names for the ninja build.

**Comment by johandc** [comment]
I'm just trying a few changes directly on the development branch from the GitHub online editor from my phone here. Excuse the mess if it doesn't work.

**Comment by johandc** [comment]
Finally fixed it. Thanks for your work

**Pull request merged**
